name: Build app

on:
  push:
    paths:
      - app/**

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: |
          cd app
          yarn

      - name: Build app
        run: |
          cd app
          yarn build
